### ISSUE TITLE
Require a sample site

### ISSUE THREAD

**Issue by debbbbie** [MauriceConrad/Photon#23]
hi, @MauriceConrad Your code is great!
But could you make a sample site like: http://photonkit.com/ , or just a github pages.
It would be better if you make one!

**Comment by debbbbie** [comment]
It looks great on electron. But I want to use it in a common browser.

Examples, macgap.

**Comment by ElyaConrad** [comment]
Yes, you are right.

There are several problems with the actual project architecture that make it hard, to compile for browser. I will implement it soon as possible.

Thank you for your effort.

**Comment by ElyaConrad** [comment]
Hey,

You inspired me and I published a simple github page at https://mauriceconrad.github.io/Photon/

At the moment, the content is very basic and bases on the github content but there is a demo app (excluding some features that require node or electron environment).
Your idea let me working on compatibility with "browserify" which is a good point. Thank you!

There is also another new feature, the `style` property that controls the UI style (e.g `cocoa`, `metro` etc.). I implemented this because I really would like to support metro or ubuntu themes in future. (AT the moment I don't have the time to implement a new theme)

Kind regards,
Maurice

**Comment by yjlin0224** [comment]
<img width="2560" alt="2018-05-04 8 44 22" src="https://user-images.githubusercontent.com/11353779/39628547-02a22944-4fdc-11e8-9ef1-210d1dd2ebd9.png">
The site seems that broken on Firefox.

**Comment by ElyaConrad** [comment]
@abc1236762 This is because, Photon 1.0 is generally not working in current version of Firefox.
This is, because Firefox currently is not supporting the specification v1 of Custom Elements. Only Chrome and Safari are currently supporting this natively. 

I implemented a workaround that makes the new spec working for browsers who do not support it yet. But there exist some problems with firefox when trying out specific feautures. I will do my best to solve this soon as possible but at the moment, the focus for the project is working in electron (and chromium).

**Comment by unmarco** [comment]
Seems broken also on the latest Chrome (stable 66.0.3359.139)
![photon-web-chrome-66](https://user-images.githubusercontent.com/6099139/39796608-c98f0a6c-5357-11e8-9e9f-baa811d025d3.png)

**Comment by MauriceConrad** [comment]
OKay, that's bad news. I also tried in Chrome 66.0.3359.139 but it works as expected.

**Comment by ElyaConrad** [comment]
@unmarco Okay, that's bad news. I also tried in Chrome 66.0.3359.139 but it works fine on my machine. The sample site also works fine in firefox for me.
What does your console say about this? Any error's?

![bildschirmfoto 2018-05-09 um 10 36 24](https://user-images.githubusercontent.com/12884009/39804727-2104aa8c-5375-11e8-9423-131babf59888.png)
**Chrome**
![bildschirmfoto 2018-05-09 um 10 37 01](https://user-images.githubusercontent.com/12884009/39804728-213ae606-5375-11e8-9d06-bf8377cd3c25.png)
**Firefox**
![bildschirmfoto 2018-05-09 um 10 37 14](https://user-images.githubusercontent.com/12884009/39804729-215d37a6-5375-11e8-8525-596b66f5902a.png)
**Safari**

**Comment by unmarco** [comment]
@MauriceConrad I think the problem is in the detail I omitted, I was on Windows, not Mac. I just tried on Chrome on my MBP and it works. As for the console, the message was "Style 'undefined' not supported".


My guess is that it was trying to use the "metro" style which is not yet there.

**Comment by ElyaConrad** [comment]
@unmarco You're completely right. THat's my mistake. I've implemented a "metro" style for debugging purposes but didn't removed the reference in the code which made it struggling on window machines.

Sorry for this, now the latest commit should remove this problem. Can you give me feedback?

**Comment by unmarco** [comment]
> Sorry for this 

No worries!

> Can you give me feedback?

@MauriceConrad Sure. I will test it later in the afternoon, at home (where my windows PC is).

**Comment by unmarco** [comment]
@MauriceConrad tested right now (same version of Chrome on windows 10) and I still get the un-rendered result and the "Style 'undefined' is not supported." error in the console.

**Comment by ElyaConrad** [comment]
@unmarco Okay, I know why. I just forgot to browserify the new code ;-) So, the browser got the old code. Now, the new code is theoretically published but it can take a few minutes to get active because I get my code from the original repo using rawgit.com (which caches everything). Just wait certain time and than, I hope everything works as expected

**Comment by ElyaConrad** [comment]
Okay, I finally tried it out on windows myself. It seems to work in Chrome generally with the exception that the progress bar and some other features do not look like on a mac. That's sad and I will try to close this issue but at the first, the focus on windows should be a metro UI. (I am not a windows dev, therefore I need someones help in CSS theming who is more familiar with windows 10 and metro). That the framework does not work in Edge is because Edge does not support some features I use in my code..
